on: [push, pull_request]

name: Check CMake install

jobs:
  install:
    runs-on: "Ubuntu latest"

    steps:
    - uses: actions/checkout@v3

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Configure the build
      run: cmake -S . -B build

    - name: Install the library
      run: cmake --install build

    - name: Test downstream usage
      run: |
        mkdir _downstream
        touch _downstream/source.cpp
        echo "cmake_minimum_required(VERSION 3.24)" > _downstream/CMakeLists.txt
        echo "project(test)" >> _downstream/CMakeLists.txt
        echo "add_executable(whee source.cpp)" >> _downstream/CMakeLists.txt
        echo "find_package(tatami_tatami)" >> _downstream/CMakeLists.txt
        echo "target_link_libraries(whee tatami::tatami)" >> _downstream/CMakeLists.txt
        cd _downstream && cmake -S . -B build
