on: [push, pull_request]

name: Run gallery code

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC", artifact: "Linux.tar.xz",
            os: ubuntu-latest
          }
        - {
            name: "macOS Latest Clang", artifact: "macOS.tar.xz",
            os: macos-latest
          }

    steps:
    - uses: actions/checkout@v1

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Configure the build
      run: cmake -DBUILD_TESTING=OFF -DBUILD_TATAMI_GALLERY=ON -S . -B build

    - name: Run the build
      run: cmake --build build

    - name: Run the no-argument tests
      run: | 
        cd build/gallery
        for x in char2double colsums parallel sparse_workspace
        do
            echo "#### RUNNING ${x} ####"
            echo
            ./${x}
            echo
        done

    - name: Run the MatrixMarket reader
        x=read_mm
        echo "#### RUNNING ${x} ####"
        echo
        printf "%% MatrixMarket\n10 10 3\n1 1 1\n2 2 2\n3 3 4\n" > test.mtx
        ./${x} test.mtx
